# settings.py - обновленная версия

"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {  # Логгер для вашего приложения
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Измените на INFO в продакшене
            'propagate': False,
        },
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)str2j1-od*djq2p=#i8zma&sgyc@#^b=+s3fpcyioc*3@b=d7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'tbs-server-s7vy.onrender.com',
    '127.0.0.1',
    'localhost',
    'k90908k8.beget.tech',
]
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Оставляем, но настроим на использование файлов/кэша
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'handlers',
    'accounts',
    'tgcloud',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_CREDENTIALS = True

# Разрешаем все домены для CORS (для тестирования, в продакшене укажите конкретные)
CORS_ALLOW_ALL_ORIGINS = True

# ИЛИ укажите конкретные домены:
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://k90908k8.beget.tech',
    'https://k90908k8.beget.tech',
    'https://tbs-server-s7vy.onrender.com',
    'http://tbs-server-s7vy.onrender.com',
]

# Для разработки можно использовать это:
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        'https://k90908k8.beget.tech',
        'https://tbs-server-s7vy.onrender.com',
    ]

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = 'https://tbs-server-s7vy.onrender.com/oauth/google/callback/'

# Настройки сессий для работы без БД (используем файлы)
SESSION_ENGINE = 'django.contrib.sessions.backends.file'  # Используем файловые сессии
SESSION_FILE_PATH = os.path.join(BASE_DIR, 'session_files')  # Папка для файлов сессий
SESSION_COOKIE_NAME = 'user_session'
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 дней
SESSION_COOKIE_SECURE = not DEBUG  # True для HTTPS в продакшене, False для разработки
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'  # Для кросс-доменных запросов нужен 'None'
SESSION_COOKIE_DOMAIN = None  # Оставляем None для текущего домена

# Настройки CSRF - КРИТИЧЕСКИ ВАЖНЫ!
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_AGE = 31449600  # 1 год в секундах
CSRF_COOKIE_SECURE = not DEBUG  # True для HTTPS в продакшене
CSRF_COOKIE_HTTPONLY = False  # Должно быть False для доступа JavaScript к CSRF токену
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'  # 'None' для кросс-доменных запросов
CSRF_USE_SESSIONS = False  # Хранить CSRF токен в cookie, не в сессии (важно!)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://k90908k8.beget.tech',
    'https://k90908k8.beget.tech',
    'https://tbs-server-s7vy.onrender.com',
    'http://tbs-server-s7vy.onrender.com',
]

# Дополнительные заголовки для CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-session-token',
    'access-control-allow-origin',
    'access-control-allow-credentials',
]

# Разрешаем методы CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# УДАЛИТЕ ИЛИ ЗАКОММЕНТИРУЙТЕ DATABASES если не используете БД Django
# Или создайте простую SQLite базу для сессий:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Создаем папку для файлов сессий если ее нет
if SESSION_ENGINE == 'django.contrib.sessions.backends.file':
    os.makedirs(SESSION_FILE_PATH, exist_ok=True)

# Дополнительные настройки безопасности
if not DEBUG:
    # В продакшене включаем дополнительные настройки безопасности
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Для кросс-доменных запросов с куками
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
else:
    # Настройки для разработки
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False